#!/usr/bin/env bash

#Get hdd info (hourly)
#Dependency: smartmontools
#Store values in files (~/serverStatus/hdd.list & ~/serverStatus/smart.val)
#File paths
HDDLIST='/tmp/serverStatus/hdd.list'
SMARTFILE='/tmp/serverStatus/smart.val'

#Check if temp folder exists, else create it
DIREC='/tmp/serverStatus'
if [ ! -d "$DIREC" ]; then
	mkdir /tmp/serverStatus
fi

#HDD_NAME(mount point, SerialNumber)
#HDD_SPACE(FREE/USED/TOTAL)
#HDD_TEMP(MAX/MIN/AVG)
#HDD_SMART(On_hours, SMART selftest)

#Reset smart.val file with current hour
date +%H > $SMARTFILE

#write filesystems to hdd.list
sudo smartctl --scan | awk '{print $1}' > $HDDLIST

#Loop through all HDDs
while read HDD
do
	##HDD_NAME
	fileSystemP=$HDD
	serialNumber=$(sudo smartctl --info $HDD | grep -e 'Serial Number' | awk '{print $3}')
	
	#HDD_SPACE
	hddSpace=$(sudo df -h $HDD | tail -1 | awk '{print $4 "\n" $3 "\n" $2}')
	
	#HDD_TEMP (needs another script to update temperature data, averages etc)
	
	#HDD_SMART
		#PASSED
		hddHealth=$(sudo smartctl -H $HDD | grep 'overall-health' | cut -d ":" -f 2-)
		#ON_HOURS
		hddONHOURS=$(sudo smartctl --all $HDD | grep 'Power_On_Hours' | awk '{print $10}')


	#Print info
	echo "$fileSystemP" >> $SMARTFILE
	echo "$serialNumber" >> $SMARTFILE
	echo "$hddSpace" >> $SMARTFILE
	echo "$hddHealth" >> $SMARTFILE
	echo "$hddONHOURS" >> $SMARTFILE

done < $HDDLIST
